# Curated portal URLs (verified fetchable 2026-05) + task stems for B4 task_bank.
# task_source is the authoritative landing page or policy hub for the topic.

PUBLIC_SERVICE_URLS = [
    "https://www.gov.cn/gongbao/2025/issue_12266/202509/content_7039598.html",
    "https://www.nhsa.gov.cn/col/col114/index.html",
    "https://www.nhsa.gov.cn/col/col105/index.html",
    "https://www.nhsa.gov.cn/col/col104/index.html",
    "https://www.nhsa.gov.cn/col/col109/index.html",
    "https://www.gov.cn/zhengce/zuixin/",
    "https://www.gov.cn/hudong/index.htm",
    "https://www.moe.gov.cn/jyb_xxgk/moe_1777/moe_1778/",
    "https://www.moe.gov.cn/jyb_xwfb/xw_fbbm/",
    "https://www.mem.gov.cn/",
    "https://www.mem.gov.cn/yw/zdgz/ajfb/",
    "https://www.samr.gov.cn/",
    "https://www.samr.gov.cn/zw/zwfb/",
    "https://www.mnr.gov.cn/",
    "https://www.mee.gov.cn/",
    "https://www.mee.gov.cn/zcwj/gwywj/202508/t20250827_1126207.shtml",
    "https://www.mca.gov.cn/",
    "https://www.mca.gov.cn/n152/n165/c166/",
    "https://www.mohrss.gov.cn/SYrlzyhshbzk/",
    "https://www.mohrss.gov.cn/SYrlzyhshbzb/jycyz/",
    "https://www.ndrc.gov.cn/",
    "https://www.ndrc.gov.cn/fggz/",
    "https://www.mof.gov.cn/",
    "https://www.mof.gov.cn/zhengwuxinxi/caizhengxinwen/",
    "https://www.nhc.gov.cn/",
    "https://www.nhc.gov.cn/wjw/bmgz/",
    "https://www.moj.gov.cn/",
    "https://www.moj.gov.cn/pub/sfbgw/",
    "https://www.mps.gov.cn/",
    "https://www.mps.gov.cn/n2253534/n2253535/",
    "https://www.ccdi.gov.cn/",
]

PUBLIC_SERVICE_STEMS = [
    "职工基本医疗保险参保人员办理异地就医备案前，应核对哪些关键信息与材料？",
    "城乡居民医保参保缴费期与待遇享受期衔接，应注意哪些常见误区？",
    "门诊慢特病资格认定与报销流程，一般包含哪些环节？",
    "生育保险待遇申领通常需要哪些证明材料与办理渠道？",
    "医疗救助对象认定与“一站式”结算，政策要点有哪些？",
    "长期护理保险试点地区参保人如何了解本地待遇与评估流程？",
    "医保电子凭证与实体社保卡在就医结算中的关系如何理解？",
    "谈判药品“双通道”供药机制对参保患者意味着什么？",
    "医保基金监管举报投诉渠道与受理范围一般包括哪些？",
    "跨省异地就医直接结算失败时，可按什么顺序自查原因？",
    "国家组织药品集中带量采购对参保人药费负担的影响应如何客观表述？",
    "基本公共卫生服务与基本医疗服务在制度上如何区分？",
    "传染病疫情信息报告与个人隐私保护之间如何把握平衡？",
    "学校传染病防控中家校协同的常见要点有哪些？",
    "预防接种异常反应补偿与民事赔偿关系应如何向群众解释？",
    "精神卫生法框架下严重精神障碍患者服务管理要点是什么？",
    "突发公共卫生事件分级响应启动后，社区可承担哪些配合工作？",
    "食品安全事故信息通报与舆情回应应注意哪些原则？",
    "饮用水水源保护区管理中的公众参与方式有哪些？",
    "噪声污染防治中“敏感建筑物集中区域”监管要点是什么？",
    "生活垃圾分类投放、收集、运输的责任边界如何划分？",
    "危险废物经营许可证制度对产废单位意味着什么？",
    "土壤污染风险管控和修复活动中的信息公开要求有哪些？",
    "碳排放权交易与排污许可制度在监管对象上如何区分？",
    "生态保护红线内允许的人类活动类型有哪些概括性限制？",
    "海域使用论证与海洋环境影响评价在程序上如何衔接？",
    "养老机构备案与消防审验的常见合规要点有哪些？",
    "未成年人社会保护工作中强制报告制度的适用情形有哪些？",
    "最低生活保障家庭经济状况核对应注意哪些隐私与准确性问题？",
    "临时救助与低保在对象与给付方式上有何主要区别？",
    "特困人员供养与分散供养服务协议应关注哪些条款？",
    "残疾人两项补贴资格认定与动态复核要点是什么？",
    "婚姻登记“跨省通办”试点中当事人材料准备要点有哪些？",
    "收养登记评估与收养能力评估有何制度性区别？",
    "慈善组织信息公开与募捐备案应关注哪些合规点？",
    "志愿服务记录与证明出具应遵循哪些基本要求？",
    "行政区划变更公告后，证照与合同地址条款如何处理更稳妥？",
    "地名管理中对具有重要地理方位意义的名称命名更名程序要点？",
    "基层群众性自治组织与基层政府在社区治理中的职责边界？",
    "信访事项受理与办理“三个到位”应如何向群众解释？",
    "行政复议与行政诉讼在救济路径选择上如何把握？",
    "政府信息公开申请中“三需要”原则应如何准确理解？",
    "重大行政决策公众参与与专家论证如何组织更规范？",
    "行政执法公示制度中应重点公开哪些要素？",
    "行政裁量权基准制定中如何听取市场主体意见？",
    "数字政府建设中政务数据共享与数据安全如何统筹？",
    "一体化政务服务平台“跨省通办”事项清单动态管理要点？",
    "电子证照法律效力与纸质证照关系应如何向企业说明？",
    "政务服务“好差评”结果在绩效考核中如何合理使用？",
    "公共资源交易平台整合共享对企业投标成本有何影响？",
    "工程建设项目审批制度改革中并联审批的关键点？",
    "企业开办“一窗通”涉及哪些部门数据协同？",
    "不动产登记“带押过户”适用前提与风险提示有哪些？",
    "户籍迁移“跨省通办”常见材料与办理时限应如何提示群众？",
    "居住证积分与公共服务挂钩政策解读应注意哪些边界？",
    "港澳居民在内地（大陆）参加社保的政策要点有哪些？",
    "华侨回国定居登记与身份衔接应注意哪些材料？",
    "外国人来华工作许可与居留许可衔接办理要点？",
    "领事保护与协助的启动条件与求助渠道有哪些？",
    "国家安全教育进社区活动可设计哪些互动环节？",
    "反间谍安全防范重点单位名录管理要点是什么？",
    "数据出境安全评估与个人信息出境标准合同路径如何区分？",
    "关键信息基础设施认定对运营者的额外义务有哪些？",
    "网络安全等级保护测评与商用密码应用安全性评估关系？",
    "政务云服务商安全责任边界在合同中如何约定更稳妥？",
    "重大活动网络安全保障工作方案通常包含哪些模块？",
    "网络谣言治理中平台与监管部门的协同要点？",
    "未成年人网络保护中监护人指导责任如何落实？",
    "网络直播营销中商品信息披露的底线要求有哪些？",
    "算法推荐服务透明化与用户关闭权应如何向用户解释？",
    "个人信息保护法下的“单独同意”在哪些场景常见？",
    "生物识别信息处理的最小必要原则如何举例说明？",
    "政务热线与12345平台工单分拨规则应向群众说明哪些点？",
]

ENTERPRISE_URLS = [
    "https://www.chinatax.gov.cn/",
    "https://www.chinatax.gov.cn/chinatax/n810219/n810724/c5247328/content.html",
    "https://www.samr.gov.cn/",
    "https://www.samr.gov.cn/zw/zwfb/",
    "https://www.ndrc.gov.cn/",
    "https://www.ndrc.gov.cn/fggz/",
    "https://www.mof.gov.cn/",
    "https://www.mof.gov.cn/zhengwuxinxi/zhengcefabu/",
    "https://www.mee.gov.cn/",
    "https://www.customs.gov.cn/",
    "https://www.customs.gov.cn/customs/302249/zfxxgk/",
    "https://www.cbirc.gov.cn/",
    "https://www.cbirc.gov.cn/cn/view/pages/index/index.html",
    "https://www.csrc.gov.cn/",
    "https://www.csrc.gov.cn/pub/newsite/",
    "https://www.safe.gov.cn/",
    "https://www.safe.gov.cn/safe/",
    "https://www.ndrc.gov.cn/fggz/fzzlgh/",
    "https://www.samr.gov.cn/bw/",
    "https://www.chinatax.gov.cn/chinatax/n810341/n810755/",
    "https://www.miit.gov.cn/",
    "https://www.miit.gov.cn/gxsj/index.html",
    "https://www.miit.gov.cn/zwgk/zcwj/wjfb/",
    "https://www.mof.gov.cn/zhengwuxinxi/caizhengxinwen/",
    "https://www.mee.gov.cn/ywgt/",
    "https://www.sac.gov.cn/",
    "https://www.cnca.gov.cn/",
    "https://www.stats.gov.cn/",
    "https://www.stats.gov.cn/tjsj/",
    "https://www.chinatax.gov.cn/chinatax/n810341/n810760/",
    "https://www.gov.cn/zhengce/zuixin/",
]

ENTERPRISE_STEMS = [
    "研发费用加计扣除政策享受中，留存备查资料一般应包含哪些类别？",
    "高新技术企业认定条件中，知识产权与研发费用的匹配性应如何理解？",
    "小型微利企业所得税优惠政策与资产总额、从业人数指标如何把握？",
    "增值税留抵退税政策适用行业与信用条件应如何向企业说明？",
    "电子发票全流程应用对企业内控与归档的影响要点？",
    "出口退税申报中“单证备案”目录与保存期限应如何提示企业？",
    "关联交易同期资料准备义务触发条件有哪些概括性表述？",
    "转让定价调查中可比公司筛选应注意哪些方法边界？",
    "企业合并重组特殊性税务处理的主要适用前提？",
    "资产损失税前扣除申报方式与证据材料要求要点？",
    "股权激励企业所得税递延纳税政策适用对象与条件？",
    "跨境服务增值税零税率与免税政策如何选择更稳妥？",
    "对外支付税务备案与源泉扣缴义务衔接要点？",
    "税收协定受益所有人判定中的“实质重于形式”如何举例？",
    "一般反避税条款适用中“合理商业目的”应如何把握？",
    "反垄断经营者集中申报营业额计算口径要点？",
    "纵向垄断协议“安全港”规则适用应注意哪些边界？",
    "滥用市场支配地位行为认定中相关市场界定方法？",
    "公平竞争审查制度对地方政府招商引资条款的影响？",
    "商业秘密保护行政执法与民事诉讼救济路径比较？",
    "企业标准自我声明公开与强制性标准关系如何说明？",
    "强制性产品认证目录调整对企业合规的影响？",
    "缺陷产品召回信息发布与消费者权益保护衔接？",
    "价格监督检查中明码标价违法行为常见情形？",
    "广告绝对化用语执法中的合理例外如何提示企业？",
    "互联网平台“二选一”行为反垄断风险点？",
    "数据造假骗取财政补贴可能涉及的法律责任类型？",
    "政府采购供应商资格条件设置的合规底线？",
    "招标投标中串通投标认定要素应如何概括？",
    "固定资产投资项目节能审查与环评批复在程序上的关系？",
    "外商投资项目核准与备案管理适用范围要点？",
    "企业债券注册制下信息披露义务人责任边界？",
    "上市公司重大资产重组停牌与复牌规则应关注哪些披露点？",
    "内幕信息知情人登记管理制度的落地要点？",
    "上市公司年报中“重要事项”章节通常涵盖哪些主题？",
    "环境信息披露管理办法对重点排污单位的要求？",
    "排污许可证变更与重新申请触发情形？",
    "碳排放配额清缴履约与抵销机制如何向企业解释？",
    "清洁生产审核强制性企业名单确定程序要点？",
    "工业产品生产许可证制度改革后监管重点转移？",
    "计量器具型式批准与检定校准关系？",
    "标准化试点示范项目申报常见材料清单？",
    "国家质量基础设施（NQI）对企业质量提升的含义？",
    "工业互联网标识解析二级节点建设对企业的作用？",
    "关键软件产品首版次保险补偿机制政策意图？",
    "首台（套）重大技术装备保险补偿项目申报要点？",
    "制造业单项冠军企业培育评价指标方向性描述？",
    "专精特新“小巨人”企业复核常见问题？",
    "工业设计中心认定对知识产权与人才指标要求？",
    "智能制造能力成熟度评估等级含义应如何向企业解释？",
    "工业互联网平台互联互通标准对企业集成的意义？",
    "产业链供应链韧性提升政策工具箱可包含哪些类型措施？",
    "重大技术装备攻关工程组织方式与产学研协同要点？",
    "制造业数字化转型中数据主权的合同条款关注点？",
    "绿色工厂评价与绿色产品认证关系？",
    "工业节能监察中单位产品能耗限额标准适用？",
    "淘汰落后产能工作验收资料准备要点？",
    "技改贴息贷款项目申报与绩效目标设置？",
    "产业基础再造工程支持领域概括？",
    "国家制造业创新中心建设运行评价要点？",
    "企业技术中心认定与创新投入指标关系？",
    "工业设计赋能制造业高质量发展案例归纳维度？",
    "服务型制造示范企业遴选关注的服务收入占比？",
    "制造业质量管理数字化典型场景？",
    "供应链创新与应用试点终期验收关注点？",
    "先进制造业集群竞赛性遴选答辩常见问题？",
    "制造业人才支持计划与职称评审衔接？",
    "产教融合型企业建设培育入库条件？",
    "制造业投融资对接活动中企业路演材料要点？",
    "工业企业技术改造和设备更新再贷款政策适用边界？",
    "制造业中试平台建设对缩短创新周期的意义？",
    "重大产业项目用地用能要素保障协调机制？",
    "先进制造业与现代服务业融合试点业态模式？",
]

MANUFACTURING_URLS = [
    "https://www.mem.gov.cn/",
    "https://www.mem.gov.cn/yw/zdgz/ajfb/",
    "https://www.mem.gov.cn/yw/zdgz/yjgl/",
    "https://www.chinasafety.gov.cn/",
    "https://www.gov.cn/zhengce/zuixin/",
    "https://www.samr.gov.cn/",
    "https://www.mee.gov.cn/",
    "https://www.miit.gov.cn/",
    "https://openstd.samr.gov.cn/",
    "https://www.gb688.cn/",
    "https://www.mem.gov.cn/gk/zfxxgkpt/",
    "https://www.mem.gov.cn/xw/yjyw/",
    "https://www.chinasafety.gov.cn/xw/",
    "https://www.mem.gov.cn/yw/zdgz/zxaj/",
    "https://www.gov.cn/",
]

MANUFACTURING_STEMS = [
    "危险化学品企业动火作业分级管理与审批要点有哪些？",
    "粉尘爆炸危险场所电气防爆与除尘系统维护要点？",
    "有限空间作业“先通风、再检测、后作业”应如何组织落实？",
    "高处作业安全带系挂点选择与临边防护设置要点？",
    "起重机械日常点检中钢丝绳与制动器检查要点？",
    "压力容器年度检查与定期检验在内容上如何区分？",
    "锅炉运行中水位异常与汽水共腾的应急处置思路？",
    "化工装置开停车安全条件确认清单通常包含哪些模块？",
    "重大危险源包保责任制中主要负责人职责要点？",
    "双重预防机制建设中风险分级管控与隐患排查如何衔接？",
    "生产安全事故应急预案演练频次与评估改进要点？",
    "特种作业人员持证上岗与复审培训应如何管理？",
    "工贸企业有限空间辨识与警示标志设置规范要点？",
    "涉氨制冷企业液氨泄漏报警与联锁切断系统维护？",
    "铝加工（深井铸造）企业铸造井安全监测要点？",
    "钢铁企业煤气区域一氧化碳监测与个体防护要点？",
    "建筑施工坍塌风险隐患排查治理专项行动关注哪些环节？",
    "隧道施工超前地质预报与支护参数动态调整要点？",
    "盾构机开仓换刀作业气体检测与通风要求？",
    "尾矿库排洪设施检查与汛期巡查频次要点？",
    "露天矿山边坡监测雷达与人工巡查如何互补？",
    "烟花爆竹生产企业工房定员定量与防静电措施？",
    "民用爆炸物品储存库治安防范与消防设施要点？",
    "机械制造车间噪声危害控制工程措施优先级？",
    "焊接作业职业健康防护中局部排风与呼吸防护选择？",
    "冲压机械双手操纵装置与安全光栅联锁关系？",
    "自动化产线人机协作区域安全围栏与停机规则？",
    "工业机器人安全停止类别与急停回路设计要求？",
    "数控机床防护门联锁与维修模式的安全管理？",
    "压力管道泄漏带压堵漏作业的风险控制要点？",
]

EDUCATION_URLS = [
    "https://www.moe.gov.cn/jyb_xxgk/moe_1777/moe_1778/",
    "https://www.moe.gov.cn/jyb_xwfb/xw_fbbm/",
    "https://www.gov.cn/zhengce/zuixin/",
    "https://www.nhc.gov.cn/",
    "https://www.moe.gov.cn/",
    "https://www.moe.gov.cn/jyb_sjzl/",
    "https://www.moe.gov.cn/jyb_xwfb/",
    "https://www.moe.gov.cn/jyb_xxgk/",
    "https://www.moe.gov.cn/jyb_sjzl/moe_560/",
    "https://www.moe.gov.cn/jyb_xwfb/s271/",
]

EDUCATION_STEMS = [
    "普通高中课程标准中数学学科核心素养包含哪些维度？",
    "义务教育课程方案中“综合实践活动”与劳动教育关系如何理解？",
    "高中阶段选课走班制下学生发展指导应覆盖哪些内容？",
    "国家智慧教育公共服务平台对教师备课的典型支持场景？",
    "职业教育产教融合型企业认定对校企合作的激励要点？",
    "“双高计划”高职院校建设绩效评价关注哪些产出指标？",
    "研究生教育质量保障中导师第一责任人制度要点？",
    "高校科研诚信案件中数据处理不当的常见表现形式？",
    "国际学生招生与管理中合规审查要点？",
    "学校食品安全校长负责制落实的检查要点？",
    "学生心理健康筛查与隐私保护如何平衡？",
    "校园欺凌防治工作机制中家校沟通要点？",
    "中小学教材选用委员会组成与回避原则？",
    "国家统编教材使用范围与培训要求？",
    "特殊教育融合发展支持保障措施概括？",
    "民族地区双语教育质量提升工程关注点？",
    "乡村教师支持计划与职称倾斜政策要点？",
    "公费师范生履约任教与违约处理规则应如何向考生说明？",
    "职业教育现场工程师专项培养计划实施要点？",
    "1+X证书制度试点中课证融通路径？",
]

CODE_URLS = [
    "https://docs.python.org/3/tutorial/",
    "https://docs.python.org/3/library/stdtypes.html",
    "https://docs.python.org/3/library/functions.html",
    "https://docs.python.org/3/howto/logging.html",
    "https://docs.python.org/3/library/concurrent.futures.html",
    "https://docs.python.org/3/library/json.html",
    "https://docs.python.org/3/library/pathlib.html",
    "https://docs.python.org/3/library/itertools.html",
    "https://docs.python.org/3/library/dataclasses.html",
    "https://docs.python.org/3/library/typing.html",
]

CODE_STEMS = [
    "Python 中浅拷贝与深拷贝的区别是什么？何时应使用 copy.deepcopy？",
    "解释 Python GIL 对多线程 CPU 密集型任务的影响及常见替代方案。",
    "list.sort() 与 sorted() 的关键差异有哪些？",
    "生成器表达式与列表推导式在内存与惰性求值上的区别？",
    "contextmanager 与 with 语句配合使用的基本模式？",
    "concurrent.futures.ThreadPoolExecutor 与 ProcessPoolExecutor 选型要点？",
    "json.dumps 中 ensure_ascii=False 的使用场景？",
    "pathlib.Path 相对 os.path 的主要优势？",
    "itertools.groupby 使用前为何通常需要先排序？",
    "dataclasses.field(default_factory=list) 解决什么问题？",
    "typing.Protocol 与 ABC 在结构子类型上的区别？",
    "logging 中 Handler、Formatter、Logger 的职责划分？",
    "异常链中 raise ... from None 与 raise ... from e 的语义区别？",
    "functools.lru_cache 适用与不适用的场景？",
    "enum.Enum 与 IntEnum 的典型使用差异？",
    "collections.Counter 在频次统计中的常见坑？",
    "zip(strict=True) 在 Python 3.10+ 中的用途？",
    "match-case 结构相比 if-elif 链的可读性优势场景？",
    "asyncio.create_task 与直接 await 协对象的区别？",
    "typing.TypedDict 与 dataclass 在描述字典结构时的取舍？",
]
